import Head from 'next/head'
import { useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import SignatureCanvas from 'react-signature-canvas'

export default function Home() {

  const sign = useRef({})
  const [imgURL, setImgURL] = useState(null)

  const clear = () => sign.current.clear();
  const saveSign = () => {
    setImgURL(
      sign.current.getTrimmedCanvas().toDataURL("image/png")
    )

    console.log(
      sign.current.getTrimmedCanvas().toDataURL("image/png").split(',')[1]
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SignatureCanvas ref={sign} canvasProps={{ className: styles.sign }} velocityFilterWeight={0.2} />
        <button onClick={clear}> Limpiar </button>
        <button onClick={saveSign}> Guardar </button>

        {imgURL ? <img src={imgURL} className={styles.sign} /> : null}
        
      </main>

    </div>
  )
}
